### ISSUE TITLE
The ZhiPuAiChatModel function calling is not working

### ISSUE THREAD

**Issue by tzolov** [spring-projects/spring-ai#1078]
Current implementation of the ZhiPuAiChatModel function calling is not working. The ZhiPuAiChatModelIT#functionCallTest and ZhiPuAiChatModelIT#streamFunctionCallTest are failing
 
```
org.springframework.ai.retry.NonTransientAiException: 429 - {"error":{"code":"1113","message":"您的账户已欠费，请充值后重试。"}}
```

Follow the OpenAIChatModel implementation as a reference to implement Function Calling.

**Comment by mxsl-gr** [comment]
Hi, i have been busy with other work recently and haven't paid much attention to this project. this message means "Your account is out of funds, please recharge and try again." I think it might be because the key amount I previously provided to Mark has been used up. I just checked my `ZhiPuAI` account, and it is indeed out of funds. I also checked the `MiniMax` key I provided, and it is also out of funds.
﻿
I have recharged the `ZhiPuAI` and `MiniMax` accounts, although not with much. Additionally, the function call capabilities of `ZhiPuAI` and `MiniMax` are not very good, currently, the function call can match at most one function, so the single function calls is worked, for example, changing the message to "What's the weather like in San Francisco?". also  model `Moonshot` is similar performance. Also, these models perform somewhat worse in English contexts. They work better in Chinese contexts, which is related to the training data. These models are mainly used in mainland China. 
﻿
The `ZhipuAI`, `MiniMax` and `Moonshot` models implementation are provided by me and I am using them. If possible, please assign the issue related to missing integration tests for these models to me.
