### ISSUE TITLE
Allow observation to log errors in tracer's spans for non-web applications

### ISSUE THREAD

**Issue by tzolov** [spring-projects/spring-ai#1440]
The  Micrometer library creates, by default, a parent observation span for Spring Web applications.

But for non-web applications such as simple Boot `CommandLineRunner` or Vaadin's  `AppShellConfigurator`, it is applications responsibility to create a parent-root span to ensure that errors that happened during observation are logged with a valid trace-id.

**Comment by codefromthecrypt** [comment]
@tzolov I think intentionally only doing this for web entrypoints and not CLI has some pros and cons. It is a con for lambda or demo like apps kicked off with a cli. I was looking at @ThomasVitale spring ai using a CLI and all the ai stuff ends up in different traces unless you make visible code to do otherwise. Maybe having a flag to opt-into CliRunner auto-span like how otel does for flask CLI commands in python could be ok?
