### ISSUE TITLE
ChromaVectorStore doDelete  The return value is null

### ISSUE THREAD

**Issue by wangqingchengsg** [spring-projects/spring-ai#1529]
<img width="1011" alt="image" src="https://github.com/user-attachments/assets/c10792f6-4547-49c2-9b2b-ede7b7ccec9e">

<img width="1372" alt="image" src="https://github.com/user-attachments/assets/e3935495-1a94-4eb8-9f72-de42ed77b679">

deletedIds The return value is null

**Comment by markpollack** [comment]
I discovered this if i bumbed the version of the chroma db, there was a test failure.  ChromaVectorStoreIT.andAndSearch does a delete and the test passes with `ghcr.io/chroma-core/chroma:0.5.11` but not with `ghcr.io/chroma-core/chroma:0.5.17`

**Comment by ilayaperumalg** [comment]
After some investigation, I see that this is the result of the [change](https://github.com/chroma-core/chroma/pull/2880) introduced in [chroma:0.5.13 ](https://github.com/chroma-core/chroma/releases/tag/0.5.13). 

Since the delete operation no longer returns the deleted Ids, I will work on a fix to use the status code as a way to verify the correctness of the operation.
