### ISSUE TITLE
How InMemoryChatMemory() Works !!

### ISSUE THREAD

**Issue by account123456789** [spring-projects/spring-ai#1585]
Dear All,

I am creating a controller service class where the chatClient object is a reference in the service class.

I am using  InMemoryChatMemory() chat memory.

My question is : In case of having a rest controller with multiple user access ... will it continue to maintain each memory in a separate memory storage or it will be shared between all users ... Thanks a lot and sorry for disturbing you.

public ChatControllerService(ChatClient.Builder builder)
    {

        this.chatClient = builder
                .defaultSystem(systemPrompt)
                .defaultAdvisors(
                        new PromptChatMemoryAdvisor( new InMemoryChatMemory() ) ,
                        new SimpleLoggerAdvisor()
                )
                .build();

    }

**Comment by habuma** [comment]
The chat memory is determined by the conversation ID. Because you didn't specify otherwise, it uses the default conversation, so the chat memory is shared across all users.

But...at prompt time you can specify the conversation ID like this:

```
String conversationId = ...;

String answer = chatClient.prompt()

   ...
   
    .advisors(advisorSpec -> advisorSpec
        .param(CHAT_MEMORY_CONVERSATION_ID_KEY, conversationId))
    .call()
    .content();
```

What I didn't specify here is how `conversationId` is set. It could really be anything you want. If you only want it to be per-user, then you could just set it to the user ID and be done with it. Or if you want each user to potentially be part of multiple conversations, then you could bake up a conversation ID that is made up of the username and some other ID that represents the conversation for that user.  So long as the conversation ID is unique, then the chat interaction will take place in a that unique conversation.

**Comment by ahnissingh** [comment]
I tried the cassandra implementation of chat memory this works fine if you want users to have medium lengths chat. Otherwise use a vector store with a vector chat memory advisor
