### ISSUE TITLE
Metrics/Observability

### ISSUE THREAD

**Issue by habuma** [spring-projects/spring-ai#186]
I was thinking it might be useful (or at least interesting) if Spring AI public metrics regarding token usage via the Actuator metrics endpoint. This information comes from the `ChatResponse` (formerly known as `AiResponse`) and (I presume) from other `???Response` classes in the future when other types of interactions are supported. But I'd imagine that the best place to report it would be at the point that the response is received, that is in the various client implementations such as `OpenAiClient`.

**Comment by markpollack** [comment]
Yes, this is a big feature set.  Introducing a listener interface on the `ChatClient` is one such approach (similar to Spring Batch) as there can be many targets for this information.  I did look into some of the AI specific options is this space based on the [Emerging LLM Application Stack](https://a16z.com/emerging-architectures-for-llm-applications/) diagram and thought a listener approach would be useful to write data to these specific systems.  [Weights and Bias](https://wandb.ai/site) and [helicone](https://www.helicone.ai/). Also, in the context of 'evaluation driven development', storing the entire set of information in order to evaluate drift/accuracy/hallucination is important as well.   I do like the idea of exporting some basic metrics, such as token usage when relevant, any perhaps other information that isn't voluminous, such as number of retries (when we add retry support), or latency times.  Those might be good for micrometer style metrics that could also be expored by a Micrometer based implementation of a ChatClientListener.

I'll add this to 0.9.0 and see if we can get at least the basic interfaces/design working.

**Comment by ThomasVitale** [comment]
In https://github.com/spring-projects/spring-ai/issues/953, I shared some initial thoughts and proposals for introducing observability in Spring AI. It would be great to get your feedback about it.

**Comment by markpollack** [comment]
Closing this issue in favor of #953

**Comment by markpollack** [comment]
duplicate

**Comment by markpollack** [comment]
Closing this issue in favor of https://github.com/spring-projects/spring-ai/issues/953

**Comment by markpollack** [comment]
Closing this issue in favor of https://github.com/spring-projects/spring-ai/issues/953

**Comment by abhyudayareddy** [comment]
Submitted PR #5706 which picks up the token-usage metrics use case originally raised here.

The PR introduces a `FinOpsTokenUsageAdvisor` — a `CallAroundAdvisor` that hooks into every `ChatClient` call and records prompt/completion/total token counts as Micrometer metrics (tagged by model and operation). It auto-configures via `@AutoConfiguration` when Micrometer is on the classpath, so no boilerplate required at call sites.
