### ISSUE TITLE
Review OpenAIProperties for Embedding

### ISSUE THREAD

**Issue by markpollack** [spring-projects/spring-ai#229]
There is a circular reference in `OpenAIProperties`

```java
	public static class Embedding {

		private final OpenAiProperties openAiProperties;

```

Investigate.

**Comment by tzolov** [comment]
As with other model clients we need a dedicated property classes for the chat and the embedding models and use a common connection properties for both models:

- OpenAiConnectionProperties (baseUrl, apiKey) with prefix `spring.ai.openai.*`.
- OpenAiChatProperties (model, temperature) with prefix `spring.ai.openai.chat`.
- OpenAiEmbeddingProperties (model) with prefix `spring.ai.openai.embedding.*`

Additionally the OpenAiChatProperties and OpenAiEmbeddingProperties should be allowed to override the OpenAiConnectionProperties so that we can use the Chat model from one Provider and the Embedding model from another. For example chat OpenAi and TAS/Llama2+OpenAIAPI for embedding.
