### ISSUE TITLE
about how to import in IDEA

### ISSUE THREAD

**Issue by zrmzack** [spring-projects/spring-ai#393]
can not import using maven jar in IDEA
![1](https://github.com/spring-projects/spring-ai/assets/39054457/66b688ba-fef6-4c7f-bc52-1623bae4e84a)

**Comment by wdkang123** [comment]
try to add:
```
<dependencies>
...
</dependencies>
<repositories>
        <repository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/milestone</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>spring-snapshots</id>
            <name>Spring Snapshots</name>
            <url>https://repo.spring.io/snapshot</url>
            <releases>
                <enabled>false</enabled>
            </releases>
        </repository>
    </repositories>
<builld>
...
</build>
```
[spring-ai getting-started](https://docs.spring.io/spring-ai/reference/getting-started.html)

**Comment by tzolov** [comment]
@zrmzack, 
What do you want to do? Mind that 0.7.1-SNAPSHOT is very old and many breaking changes have happened since. 
If you are starting a new project you should use the latest [0.8.1-SNAPSHOT](https://docs.spring.io/spring-ai/reference/0.8-SNAPSHOT/index.html) or at least the latest milestone release [0.8.0](https://docs.spring.io/spring-ai/reference/index.html). 
Also check the [Add Milestone and Snapshot Repositories](https://docs.spring.io/spring-ai/reference/0.8-SNAPSHOT/getting-started.html#repositories) to configure your repositories.

**Comment by tzolov** [comment]
follow the suggestions about and the reference documentation. 
If you find any problems please reopen.
