### ISSUE TITLE
Add constructor to OpenAiEmbeddingClient that takes OpenAiEmbeddingOptions

### ISSUE THREAD

**Issue by markpollack** [spring-projects/spring-ai#447]
See https://github.com/spring-projects/spring-ai/issues/262 for initial discussion.

**Comment by emileastih1** [comment]
Can you I take this issue by creating a new PR ?

**Comment by emileastih1** [comment]
I was looking at this issue, and I think the way that the class is created is sufficient and doesn't need any change because they are using constructor chaining to initialize a new instance of the OpenAiEmbeddingClient class.

Also there is already two constructors that takes "OpenAiEmbeddingOptions".

I was thinking about adding a new method called "withDefaultOptions" like what is suggested in the spring ai documentation but this is not needed because the initialization of the default options is done withing the constructors if the user didn't specify any, so it is already handled.

Finally, I think we could update the SpringAI documentation to match the actual code of the OpenAiEmbeddingClient class, but the only thing that is bugging me is to have different APIs (To initialize a new instance) for the OpenAiEmbeddingClient  and for example OllamaEmbeddingClient which should practically be implemented in the same manner.

What do you think?

**Comment by emileastih1** [comment]
The same thing goes to OpenAiChatClient.java

**Comment by jehyn923** [comment]
Is anyone working on this issue?

**Comment by emileastih1** [comment]
Hello @jehyn923 , I am the last one who commented on this issue and was waiting for a reply from [markpollack] to check how to move forward with the issue.

**Comment by markpollack** [comment]
Apologies for my poor project management skills.  Looks like we are good now.

```
	public AzureOpenAiEmbeddingModel(OpenAIClient azureOpenAiClient, MetadataMode metadataMode,
			AzureOpenAiEmbeddingOptions options) {
```
