### ISSUE TITLE
Add MongoDB as a Vector Store

### ISSUE THREAD

**Issue by jxblum** [spring-projects/spring-ai#48]
See https://www.mongodb.com/products/platform/atlas-vector-search.

**Comment by Kirbstomper** [comment]
So I have been working on this in 
https://github.com/Kirbstomper/spring-ai/tree/feature/mongoDB_vectorStore

And while its almost done, (just need to filter on threshold), due to vector search in mongoDB being an atlas only feature, I can only really run the IT on my machine locally (although if the spring organization has a free tier, we could still incorporate it into the pipeline with some setup)
So I will probably just settle for mocking a mongo connection .
I also might add creation of the search index if it does not exist, as vector search cannot function correctly without it.

Let me know your thoughts!

**Comment by markpollack** [comment]
so we closed the [PR](https://github.com/spring-projects/spring-ai/pull/21) due to the implementation not being based on the mongodb vector search offering.  So now closing the issue.
