### ISSUE TITLE
The SDK of the vector database is very inflexible, unable to modify some database fields.

### ISSUE THREAD

**Issue by Warrior0x1** [spring-projects/spring-ai#513]
In the current version, taking the Milvus database as an example, I cannot specify the field names of the database collection. If I have a previously used collection, and if the fields do not match the current fixed fields, I cannot perform a query. I strongly suggest that custom field names should be allowed!!!

        public static final String DOC_ID_FIELD_NAME = "doc_id";

	public static final String CONTENT_FIELD_NAME = "content";

	public static final String METADATA_FIELD_NAME = "metadata";

	public static final String EMBEDDING_FIELD_NAME = "embedding";

**Comment by Warrior0x1** [comment]
The cost of rebuilding a vector database that has already been put into production in order to use Spring AI is enormous.

**Comment by iAMSagar44** [comment]
I faced a similar issue with Azure AI Search, where I had imported some data into the vector store using Azure's inbuilt solution for importing and chunking data into Azure AI Search. The import process resulted in different field names compared to the vector store implementations in Spring AI. And when I was trying to do a vector search using Spring AI, it failed. 
The only way that I could think of resolving the issue was to create your own implementation of the Vector Store and model the fields in the code with the same name as in Azure AI Search.

**Comment by markpollack** [comment]
Thanks for reporting this, sorry for the delay.   @iAMSagar44 wrt to the comment "The import process resulted in different field names compared to the vector store implementations in Spring AI."   Were the field names different or were the different fields.  I agree, we need to open up the names that are used.  A simple way would be to create setters for all the current field names, what do you think?

**Comment by AishwaryaMalagannavar** [comment]
> Thanks for reporting this, sorry for the delay. [@iAMSagar44](https://github.com/iAMSagar44) wrt to the comment "The import process resulted in different field names compared to the vector store implementations in Spring AI." Were the field names different or were the different fields. I agree, we need to open up the names that are used. A simple way would be to create setters for all the current field names, what do you think?

@markpollack, This issue persists in the AzureVectorStore and does not appear to have been resolved in the 1.0.0 release.
