### ISSUE TITLE
PgVectorStore should allow table and index name to be specified

### ISSUE THREAD

**Issue by johnsonr** [spring-projects/spring-ai#747]
It should be possible to specify a custom name for the table used by `PgVectorStore`, which is currently hardcoded to  `vector_store`. The associated index name could default to being generated based on the name while also allowing custom specification.

`PgVectorStore` is effectively a database singleton. This is not Spring-like.

Concrete reasons this would be desirable:

- It should be possible to have multiple vector stores in the same database.
- It should be possible to have a vector store within a schema. It's good practice for an app's tables to be within a schema.

**Comment by muthuishere** [comment]
I have been closely following this issue regarding enabling custom table names for the PGvector Store, and I’ve developed a solution that I believe addresses the requirements discussed here.

The solution includes:
- Adding properties to configure custom table and index names.
- Modifying the PgVectorStore class to use these configurable properties.
- Ensuring backward compatibility with setups using default settings.

I have thoroughly tested these changes to ensure they work seamlessly with both new configurations and existing deployments. I will be submitting the PR for the same

**Comment by tzolov** [comment]
Hi @johnsonr ,

Regarding the 
> It should be possible to have multiple vector stores in the same database. 
> It should be possible to have a vector store within a schema. It's good practice for an app's tables to be within a schema.

The reason for not providing parametrisable table name/schema/index is that , for convenience, we pre-create the table when not available. 
And we cannot afford dynamic DDLs as no support for prepared DDL is provided.

We could either drop the pre-creation all together or run it only when no custom table/schema/index were provided. 
For the later we would assume that the user would take care.

Would this make sense?

**Comment by muthuishere** [comment]
@tzolov Without this modification, a user will be able to create only one table in any given database. If we want to accommodate multiple embeddings of different dimensions, the user would need to have separate databases. This is because the table name remains constant in any given database.

I could see two  options:

1. Add a table name validation using matches("^[a-zA-Z0-9_]+$"). to ensure no SQL injection is there

2. Upon receiving the property spring.ai.vectorstore.pgvector.vectorTableName, ensure the table exists and the fields are available, or we can throw an exception. if its not specified use the existing flow

I would like to go for option 2

**Comment by muthuishere** [comment]
@tzolov / @johnsonr 

When revising the approach, I encountered a recurring issue related to using table names from configurations. Whether it's selecting from or deleting tables, similar to using in DDL statements, the same limitation arises: we cannot embed table names into prepared statements directly. This constraint leads us to two viable solutions:

1. Regex Sanitization: We could implement regex sanitization, which is straightforward and would ensure that the table names are safe from SQL injection threats.

2. Spring Data Approach: Alternatively, we could leverage the Spring Data methodology by introducing a specific configuration annotation called PgVectorConfiguration. This annotation would include attributes for vectorTableName and indexName. By doing so, we can integrate these configuration details directly into our codebase as static, immutable configurations, rather than external properties that could be prone to modification and injection risks.We can still do a sanity check in our library though


let me know Your thoughts , so i will start working on it.

**Comment by muthuishere** [comment]
@tzolov  

PR https://github.com/spring-projects/spring-ai/pull/872 has been updated with commits to  introduce the ability to specify custom table name for PgVectorStore, and stop pre create tables when custom table names are provided. also added tablename validations, field validations to ensure things are okay

Key changes include:
- Adding properties to configure custom table names.
- Modifying PgVectorStore to conditionally pre-create tables only when custom table names are not provided.
- Implementing table & field validation for custom configurations.
- Extensive tests to ensure compatibility with both new configurations and existing deployments.

With these changes, automatic table pre-creation is removed, and users are expected to manage table setup in custom scenarios, consistent with production environment practices.
