### ISSUE TITLE
Introduce basic starter dependency for Hugging Face

### ISSUE THREAD

**Issue by ThomasVitale** [spring-projects/spring-ai#838]
**Expected Behavior**

Hugging Face Integration Endpoints are a very convenient way to deploy machine learning models in the cloud. Spring AI provides a basic integration and autoconfiguration, but it's missing a starter dependency.

This integration is a bit special compared to the others and I'm aware that it will need some additional work to make it more configurable and flexible. Still, in the meantime, it would be really nice to start publishing a starter to enable the basic use case of calling a single chat model via an Inference Endpoint. Providing a faster and easier way to try out the Hugging Face integration could also lead to getting more feedback from the users to develop the integration further.

**Current Behavior**

Autoconfiguration for Hugging Face is defined, but there isn't a starter dependency to activate it in a straightforward way.

**Comment by eschnou** [comment]
Hi @ThomasVitale - I just filed an issue related to Hugging Face and a difference between Serverless and Inference endpoints. I think the fix is as easy to change one of the call but don't have a setup to validate this. Maybe you can have a look at well, would be great if the starter would support both serverless and inference endpoints.

https://github.com/spring-projects/spring-ai/issues/849

**Comment by ThomasVitale** [comment]
@eschnou thanks for mentioning that, I only worked with the dedicated Inference Endpoints, so I hadn't noticed there was a problem with the serverless ones. I'll have a look and perhaps update the pull request with a fix to support both.
